DROP TABLE "T_ARTICLE" CASCADE CONSTRAINTS;
DROP TABLE "T_COMMANDE" CASCADE CONSTRAINTS;
DROP TABLE "T_LOT" CASCADE CONSTRAINTS;
DROP TABLE "T_STOCK" CASCADE CONSTRAINTS;
DROP TABLE "T_USER" CASCADE CONSTRAINTS;

/* CREATION DE LA SEQUENCE POUR TABLE T_User */
DROP SEQUENCE SEQ_USER;
CREATE SEQUENCE SEQ_USER INCREMENT BY 1 START WITH 1;

/* CREATION DE LA SEQUENCE POUR TABLE T_Article */
DROP SEQUENCE SEQ_ARTICLE;
CREATE SEQUENCE SEQ_ARTICLE INCREMENT BY 1 START WITH 1;

CREATE TABLE "T_ARTICLE" 
(	"IDARTICLE" NUMBER(12) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"MARQUE" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"PRIXUNITAIRE" NUMBER(5,2) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CT_TARTICLE" PRIMARY KEY ("IDARTICLE")
);


CREATE TABLE "T_COMMANDE" 
(	"IdCommande" NUMBER(12) NOT NULL ENABLE, 
	"IdUser" NUMBER(12) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TCOMMANDE" PRIMARY KEY ("IdCommande")
);

CREATE TABLE "T_LOT" 
(	"IdLot" NUMBER(12) NOT NULL ENABLE, 
    "IdCommande" NUMBER(12) NOT NULL ENABLE,
    "IdArticle" NUMBER(12) NOT NULL ENABLE,
	"Quantite" NUMBER(12) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TLOT" PRIMARY KEY ("IdLot")
);

CREATE TABLE "T_STOCK" 
(	"IdArticle" NUMBER(12) NOT NULL ENABLE, 
	"Quantite" NUMBER(12) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TSTOCK" PRIMARY KEY ("IdArticle")
);

CREATE TABLE "T_USER" 
(	"IDUSER" NUMBER(12) NOT NULL ENABLE, 
	"LOGIN" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
    "PASS" VARCHAR2(25 BYTE) NOT NULL ENABLE,
    "NBCONNEXION" NUMBER(12) DEFAULT 0, 
	 CONSTRAINT "PK_TUSER" PRIMARY KEY ("IDUSER")
);

CREATE TABLE "T_CADDIE" 
(	"IDCADDIE" NUMBER(12) NOT NULL ENABLE, 
    "IDARTICLE" NUMBER(12) NOT NULL ENABLE,
	"QUANTITE" NUMBER(12) NOT NULL ENABLE
);

CREATE OR REPLACE TRIGGER TR_USER
    BEFORE INSERT 
    ON T_USER
    FOR EACH ROW
    BEGIN
        SELECT SEQ_USER.NEXTVAL
        INTO :NEW.IDUSER
        FROM DUAL;
    END;
/

CREATE OR REPLACE TRIGGER TR_ARTICLE
    BEFORE INSERT 
    ON T_ARTICLE
    FOR EACH ROW
    BEGIN
        SELECT SEQ_ARTICLE.NEXTVAL
        INTO :NEW.IDARTICLE
        FROM DUAL;
    END;
/

/* ------------------------------------------------------------------------ */
/* ALIMENTATION TABLES */

/* POUR TABLE T_User */
INSERT INTO T_USER VALUES (NULL,'Marleyb', 'marleyb123', 0);
INSERT INTO T_USER VALUES (NULL,'Charliep', 'charliep123', 0);
INSERT INTO T_USER VALUES (NULL,'Milesd', 'milesd123', 0);
INSERT INTO T_USER VALUES (NULL,'Keithj', 'keithj123', 0);
INSERT INTO T_USER VALUES (NULL,'philippe', 'afpa', 0);

/* POUR TABLE T_Article */
INSERT INTO T_ARTICLE VALUES (NULL,'Bonbon', 'Haribo', 0.2);
INSERT INTO T_ARTICLE VALUES (NULL,'Stylo Bleu', 'Bic', 1);
INSERT INTO T_ARTICLE VALUES (NULL,'Ramette 80 grs', 'ClaireFontaine', 5);
INSERT INTO T_ARTICLE VALUES (NULL,'Equerre', 'Castorama', 2);
INSERT INTO T_ARTICLE VALUES (NULL,'Montre', 'Rolex', 200);
INSERT INTO T_ARTICLE VALUES (NULL,'Velo', 'Decathlon', 190);
INSERT INTO T_ARTICLE VALUES (NULL,'Rameur', 'Decathlon', 290);

/* POUR TABLE T_CADDIE */
INSERT INTO T_CADDIE VALUES (1, 1, 1);
INSERT INTO T_CADDIE VALUES (2, 2, 1);
INSERT INTO T_CADDIE VALUES (3, 2, 1);
INSERT INTO T_CADDIE VALUES (4, 4, 4);
INSERT INTO T_CADDIE VALUES (5, 1, 1);
INSERT INTO T_CADDIE VALUES (5, 2, 2);
INSERT INTO T_CADDIE VALUES (5, 3, 3);
INSERT INTO T_CADDIE VALUES (5, 4, 4);
INSERT INTO T_CADDIE VALUES (6, 6, 6);
INSERT INTO T_CADDIE VALUES (6, 2, 1);

/* ------------------------------------------------------------------------ */
/* CREATION PROCEDURES */ 

/* SELECTION USER PAR ID */
CREATE or REPLACE PROCEDURE SelectUser (v_iduser NUMBER)
IS
 v_user t_user%ROWTYPE;
BEGIN
  SELECT * INTO v_user FROM T_USER WHERE IDUSER = v_iduser;
END;
/

CREATE or REPLACE PROCEDURE SelectArticle (v_idarticle NUMBER)
IS
 v_article T_ARTICLE%ROWTYPE;
BEGIN
  SELECT * INTO v_article FROM T_ARTICLE WHERE IDARTICLE = v_idarticle;
END;
/

/* VERIFIE IDENTIFIANTS DE USER */
CREATE or REPLACE FUNCTION IsValidLogon (p_login VARCHAR2 , p_motdepasse VARCHAR2)
RETURN NUMBER
IS
	iduser NUMBER;	
BEGIN
	SELECT IDUSER into iduser FROM T_USER WHERE Login=p_login AND Pass=p_motdepasse;
  RETURN iduser;
EXCEPTION
WHEN NO_DATA_FOUND THEN
  return -1;
END;
/

/* DELETE CADDIE PAR ID */
CREATE or REPLACE PROCEDURE DeleteCaddie (p_idcaddie NUMBER)
IS

BEGIN
  DELETE FROM T_CADDIE WHERE IDCADDIE = p_idcaddie;
END;
/

/* INSERE ARTICLE DANS CADDIE */
CREATE or REPLACE PROCEDURE InsertArticleCaddie (p_idcaddie NUMBER, p_idarticle NUMBER, p_nbcommande NUMBER)
IS

BEGIN
  INSERT INTO T_CADDIE VALUES (p_idcaddie,  p_idarticle,  p_nbcommande);
END;
/